import {
  Utensils,
  UtensilsCrossed,
  Coffee,
  Wine,
  Carrot,
  Pizza,
  Sandwich,
  Drumstick,
  Beer,
  Wallet,
  BadgeDollarSign,
  Salad,
  Soup,
  IceCream2,
  DoorOpen,
  Truck,
  Footprints,
  Martini,
  Accessibility,
  ChefHat,
  EggFried,
  Croissant,
  CakeSlice,
  Dessert,
} from "lucide-react";

export const filterList = [
  { id: "1", item: "Places", icon: UtensilsCrossed },
  { id: "2", item: "Cafe", icon: Coffee },
  { id: "3", item: "Bar", icon: Wine },
  { id: "4", item: "Restaurants", icon: Utensils },
  { id: "16", item: "Vegetarian", icon: Carrot },
  { id: "5", item: "Pizza", icon: Pizza },
  { id: "6", item: "Sandwich", icon: Sandwich },
  { id: "7", item: "Chicken", icon: Drumstick },
  { id: "8", item: "Beer", icon: Beer },
  { id: "17", item: "Affordable", icon: Wallet },
  { id: "18", item: "Luxury", icon: BadgeDollarSign },
  { id: "9", item: "Chinese", icon: Salad },
  { id: "10", item: "Indian", icon: Soup },
  { id: "11", item: "Italian", icon: IceCream2 },
  { id: "12", item: "Open Now", icon: DoorOpen },
  { id: "13", item: "Delivery", icon: Truck },
  { id: "14", item: "Take Out", icon: Footprints },
  { id: "15", item: "Dine In", icon: Martini },
  { id: "19", item: "Wheelchair Accessible", icon: Accessibility },
  { id: "20", item: "Reservations", icon: ChefHat },
  { id: "20", item: "Serves Breakfast", icon: EggFried },
  { id: "20", item: "Serves Brunch", icon: Croissant },
  { id: "20", item: "Serves Lunch", icon: CakeSlice },
  { id: "20", item: "Serves Dinner", icon: Dessert },
];
