export const filterList = [
  { id: "1", item: "item1", icon: "icon" },
  { id: "2", item: "item1", icon: "icon" },
  { id: "3", item: "item1", icon: "icon" },
  { id: "4", item: "item1", icon: "icon" },
  { id: "5", item: "item1", icon: "icon" },
  { id: "6", item: "item1", icon: "icon" },
  { id: "7", item: "item1", icon: "icon" },
  { id: "8", item: "item1", icon: "icon" },
  { id: "9", item: "item1", icon: "icon" },
  { id: "10", item: "item1", icon: "icon" },
  { id: "11", item: "item1", icon: "icon" },
  { id: "12", item: "item1", icon: "icon" },
  { id: "13", item: "item1", icon: "icon" },
  { id: "14", item: "item1", icon: "icon" },
  { id: "15", item: "item1", icon: "icon" },
  { id: "16", item: "item1", icon: "icon" },
  { id: "17", item: "item1", icon: "icon" },
  { id: "18", item: "item1", icon: "icon" },
  { id: "19", item: "item1", icon: "icon" },
  { id: "20", item: "item1", icon: "icon" },
];
